/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-06-09 06:37:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1591684597967L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1591619331272L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>지구력</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500|Gaegu:700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=East+Sea+Dokdo&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/aos.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/jquery.timepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/personal_css/main.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ficon.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/earlyaccess/jejugothic.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("      body{\r\n");
      out.write("        font-family: 'Poppins','Jeju Gothic', serif;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("  <!-- START nav -->\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>지구력</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  \r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/back_logo.png\" alt=\"logo\"class=\"headerclogo\"  width=\"45px\" height=\"45px\"></a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("          <li class=\"nav-item active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">환경단체</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"projectlist.do\" class=\"nav-link\">프로젝트</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">청원</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">함께해요</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">로그인</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <!-- END nav -->\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"block-31\" style=\"position: relative;\">\r\n");
      out.write("    <div class=\"owl-carousel loop-block-31 \">\r\n");
      out.write("      <div class=\"block-30 item\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_.png');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("            <div class=\"col-md-12\" style=\"text-align: center;\">\r\n");
      out.write("              <h3 class=\"heading\">\r\n");
      out.write("                SAVE THE PLANT<br>SAVE THE EARTH<br>SAVE THE WORLD<br>\r\n");
      out.write("              </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row searchbox\">\r\n");
      out.write("        <p>지금 지구력에는 <br> 20개의 환경단체와 함께하고 있습니다.</p>\r\n");
      out.write("        <button>환경단체 검색</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> <!-- 환경단체 검색 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"featured-donate overlay-color\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_2.jpg');\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h2 class=\"main_title\">인기 프로젝트</h2>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8 order-lg-2 mb-3 mb-lg-0\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bg_2.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 pr-lg-5\">\r\n");
      out.write("          <span class=\"featured-text mb-3 d-block\">Featured</span>\r\n");
      out.write("          <h2 class=\"project_title\">프로젝트 이름이 들어가는 곳</h2>\r\n");
      out.write("          <p class=\"mb-3\">프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다.프로젝트 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("          <span class=\"donation-time mb-3\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("          <div class=\"progress custom-progress\">\r\n");
      out.write("            <div class=\"progress-bar bg-warning\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <span class=\"fund-raised d-block mb-5\">1,562,400원 / 9,900,000원</span>\r\n");
      out.write("          <p><a href=\"#\" class=\"btn btn-primary btn-hover-white py-3 px-5\">기 부 하 기</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div> <!-- 인기 프로젝트 -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-section fund-raisers\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row mb-5\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("          <h2>진행중인 프로젝트</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-12 block-11\">\r\n");
      out.write("          <div class=\"nonloop-block-11 owl-carousel\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_1.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">프로젝트 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">1,562,400원 / 9,900,000원</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_1.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">프로젝트 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">1,562,400원 / 9,900,000원</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_1.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">프로젝트 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">1,562,400원 / 9,900,000원</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_1.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">프로젝트 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">1,562,400원 / 9,900,000원</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_1.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">프로젝트 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다. 프로젝트 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">1,562,400원 / 9,900,000원</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> <!-- 진행중인 프로젝트 -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-section fund-raisers\" style=\"background: #fafafa;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row mb-5\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("          <h2>진행중인 청원</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-12 block-11\">\r\n");
      out.write("          <div class=\"nonloop-block-11 owl-carousel\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_2.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">청원 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">354명</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_2.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">청원 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">354명</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_2.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">청원 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">354명</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_2.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">청원 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">354명</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card fundraise-item\">\r\n");
      out.write("              <a href=\"#\"><img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_2.jpg\" alt=\"Image placeholder\"></a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3 class=\"card-title\"><a href=\"#\">청원 이름</a></h3>\r\n");
      out.write("                <p class=\"card-text\">청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다. 청원 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("                <span class=\"donation-time mb-3 d-block\">2020.03.17 ~ 2020.06.15까지</span>\r\n");
      out.write("                <div class=\"progress custom-progress-success\">\r\n");
      out.write("                  <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"fund-raised d-block\">354명</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> <!-- 진행중인 청원 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-section fund-raisers\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row mb-5\">\r\n");
      out.write("        <div class=\"col-md-12 text-center\" style=\"text-align: left !important;\">\r\n");
      out.write("          <h2>최대 후원자</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6 col-lg-3 mb-5\">\r\n");
      out.write("          <div class=\"person-donate text-center bg-light pt-4\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            <div class=\"donate-info\">\r\n");
      out.write("              <h2>홍길동</h2>\r\n");
      out.write("              <span class=\"time d-block mb-3\">2시간 전 기부</span>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"donate-amount d-flex\">\r\n");
      out.write("                <div class=\"label\">기부금</div>\r\n");
      out.write("                <div class=\"amount\">30,000원</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 col-lg-3 mb-5\">\r\n");
      out.write("          <div class=\"person-donate text-center bg-light pt-4\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            <div class=\"donate-info\">\r\n");
      out.write("              <h2>홍길동</h2>\r\n");
      out.write("              <span class=\"time d-block mb-3\">2시간 전 기부</span>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"donate-amount d-flex\">\r\n");
      out.write("                <div class=\"label\">기부금</div>\r\n");
      out.write("                <div class=\"amount\">30,000원</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 col-lg-3 mb-5\">\r\n");
      out.write("          <div class=\"person-donate text-center bg-light pt-4\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            <div class=\"donate-info\">\r\n");
      out.write("              <h2>홍길동</h2>\r\n");
      out.write("              <span class=\"time d-block mb-3\">2시간 전 기부</span>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"donate-amount d-flex\">\r\n");
      out.write("                <div class=\"label\">기부금</div>\r\n");
      out.write("                <div class=\"amount\">30,000원</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 col-lg-3 mb-5\">\r\n");
      out.write("          <div class=\"person-donate text-center bg-light pt-4\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/person_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            <div class=\"donate-info\">\r\n");
      out.write("              <h2>홍길동</h2>\r\n");
      out.write("              <span class=\"time d-block mb-3\">2시간 전 기부</span>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"donate-amount d-flex\">\r\n");
      out.write("                <div class=\"label\">기부금</div>\r\n");
      out.write("                <div class=\"amount\">30,000원</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> <!-- 최대 후원자 -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-section bg-light\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row mb-5\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("          <h2>함께해요</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"post-entry\">\r\n");
      out.write("            <a href=\"#\" class=\"mb-3 img-wrap\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_4.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("              <span class=\"date\">2020. 06. 15</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <h3><a href=\"#\">봉사활동 이름</a></h3>\r\n");
      out.write("            <p>봉사활동 내용이 들어가는 곳입니다. 봉사활동 내용이 들어가는 곳입니다. 봉사활동 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("            <p><a href=\"#\">자세히 보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"post-entry\">\r\n");
      out.write("            <a href=\"#\" class=\"mb-3 img-wrap\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_4.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("              <span class=\"date\">2020. 06. 15</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <h3><a href=\"#\">봉사활동 이름</a></h3>\r\n");
      out.write("            <p>봉사활동 내용이 들어가는 곳입니다. 봉사활동 내용이 들어가는 곳입니다. 봉사활동 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("            <p><a href=\"#\">자세히 보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"post-entry\">\r\n");
      out.write("            <a href=\"#\" class=\"mb-3 img-wrap\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/img_4.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("              <span class=\"date\">2020. 06. 15</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <h3><a href=\"#\">봉사활동 이름</a></h3>\r\n");
      out.write("            <p>봉사활동 내용이 들어가는 곳입니다. 봉사활동 내용이 들어가는 곳입니다. 봉사활동 내용이 들어가는 곳입니다.</p>\r\n");
      out.write("            <p><a href=\"#\">자세히 보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> <!-- 함께해요 -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- START footer -->\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>지구력</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body> \r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row mb-5\">\r\n");
      out.write("        <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("          <h3 class=\"heading-section\">About Us</h3>\r\n");
      out.write("          <p class=\"mb-5\">지구력(지구를 지키는 세력)은 국내 환경분야 <br>비영리 민간단체 공공 데이터를 활용하여 환경 <br>단체의 통합정보를 제공하고, 해당단체가 <br>진행하는 프로젝트를 후원 및 소통할 수 있는 <br>참여형 환경 온라인 플랫폼이다.</p>\r\n");
      out.write("          <p><a href=\"#\" class=\"btn btn-primary px-4 py-3\">참 여 하 기</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 col-lg-4\" style=\"padding-left: 60px;\">\r\n");
      out.write("          <h3 class=\"heading-section\">Member</h3>\r\n");
      out.write("          <div class=\"block-21 d-flex mb-4\">\r\n");
      out.write("            <div class=\"text\">\r\n");
      out.write("              <h3 class=\"heading\" style=\"color: #fff;\">PM&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;김솔지</h3><br>\r\n");
      out.write("              <h3 class=\"heading\" style=\"color: #fff;\">PE&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp;&nbsp;김원중&nbsp;&nbsp;&nbsp;&nbsp;안지민</h3><br>\r\n");
      out.write("              <h3 class=\"heading\" style=\"color: #fff;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;윤대형&nbsp;&nbsp;&nbsp;&nbsp;이재원</h3><br>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("          <div class=\"block-23\">\r\n");
      out.write("            <h3 class=\"heading-section\">Contact Info</h3>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">서울특별시 강남구 테헤란로14길 6 <br>남도빌딩</span></li>\r\n");
      out.write("                <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">1544 9970</span></a></li>\r\n");
      out.write("                <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">PowerRangers@naver.com</span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row pt-5\">\r\n");
      out.write("        <div class=\"col-md-12 text-center\">\r\n");
      out.write("          <p>\r\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("            COPYRIGHT © 2020 Power Rangers ALL RIGHTS RESERVED.\r\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <!-- END footer -->\r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
